baseURL = 'https://aaronbroyer.com'
languageCode = 'en-us'
title = 'Aaron Royer'
theme = 'hugo-ivy'


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 2

    [[menu.main]]
        name = "Curios"
        url = "/curios/"
        weight = 3


[params]
    description = 'Learning / Code / Curiosity'
    footer = "&copy; {Year}"

