name: Deploy Personal Siteto Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t aaronbroyer .

      - name: Copy files to Lightsail
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "Dockerfile"
          target: "/home/ubuntu/aaronbroyer"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd ~/aaronbroyer
            docker build -t aaronbroyer .
            docker rm -f aaronbroyer || true
            docker run -d -p 80:80 --name aaronbroyer aaronbroyer
